clear
clc
imgFolderTrain = '.\square\Training_Set\';
imgFolderTest =  '.\square\Test_Set\';
imgSetTrain = [imageSet(fullfile(imgFolderTrain,'Appendicularia')), ...
               imageSet(fullfile(imgFolderTrain,'Bubble')), ...
               imageSet(fullfile(imgFolderTrain,'Chaetognatha')), ...
               imageSet(fullfile(imgFolderTrain,'CladoceraPenilia')), ...
               imageSet(fullfile(imgFolderTrain,'Copepoda')), ...
               imageSet(fullfile(imgFolderTrain,'Decapoda')), ...
               imageSet(fullfile(imgFolderTrain,'Doliolida')), ...
               imageSet(fullfile(imgFolderTrain,'Egg')), ...
               imageSet(fullfile(imgFolderTrain,'Fiber')), ...
               imageSet(fullfile(imgFolderTrain,'Gelatinous')), ...
               imageSet(fullfile(imgFolderTrain,'Multiple')), ...
               imageSet(fullfile(imgFolderTrain,'Nonbio')), ...
               imageSet(fullfile(imgFolderTrain,'Pteropoda'))];
imgSetTest = [imageSet(fullfile(imgFolderTest,'Appendicularia')), ...
              imageSet(fullfile(imgFolderTest,'Bubble')), ...
              imageSet(fullfile(imgFolderTest,'Chaetognatha')), ...
              imageSet(fullfile(imgFolderTest,'CladoceraPenilia')), ...
              imageSet(fullfile(imgFolderTest,'Copepoda')), ...
              imageSet(fullfile(imgFolderTest,'Decapoda')), ...
              imageSet(fullfile(imgFolderTest,'Doliolida')), ...
              imageSet(fullfile(imgFolderTest,'Egg')), ...
              imageSet(fullfile(imgFolderTest,'Fiber')), ...
              imageSet(fullfile(imgFolderTest,'Gelatinous')), ...
              imageSet(fullfile(imgFolderTest,'Multiple')), ...
              imageSet(fullfile(imgFolderTest,'Nonbio')), ...
              imageSet(fullfile(imgFolderTest,'Pteropoda'))];
bag = bagOfFeatures(imgSetTrain);
% load('bag.mat');
categoryClassifier = trainImageCategoryClassifier(imgSetTrain, bag);
confMatrixTrain = evaluate(categoryClassifier, imgSetTrain);
% load('categoryClassifier.mat');
confMatrixTest = evaluate(categoryClassifier, imgSetTest);
writeData(confMatrixTrain,'confMatrixTrain.txt');
writeData(confMatrixTest,'confMatrixTest.txt');
